### ISSUE TITLE
`add` seems that it is worked is different from version 2?

### ISSUE THREAD

**Issue by VonFry** [olivernn/lunr.js#254]
`add` seems that it is worked is different from version 2?

The same code and json data can be run correctly in version `1.0.0`, but it cannot be run in version `2.0.0`. And I cannot find any question in my code.

expection is here:
```
TypeError: Cannot read property '1' of undefined
    at e.Builder.add (cdnjs.cloudflare.com/ajax/libs/lunr.js/2.0.0/lunr.min.js:6)
    at e.Builder.<anonymous> (:4000/assets/js/search.js:49)
    at e (cdnjs.cloudflare.com/ajax/libs/lunr.js/2.0.0/lunr.min.js:6)
    at :4000/assets/js/search.js:36
    at _4ec (dojo.js:15)
    at _4e6 (dojo.js:15)
    at _4eb.resolve (dojo.js:15)
    at _4f2 (dojo.js:15)
    at _4ec (dojo.js:15)
    at _4e6 (dojo.js:15) "TypeError: Cannot read property '1' of undefined
    at e.Builder.add (https://cdnjs.cloudflare.com/ajax/libs/lunr.js/2.0.0/lunr.min.js:6:14950)
    at e.Builder.<anonymous> (http://localhost:4000/assets/js/search.js:49:30)
    at e (https://cdnjs.cloudflare.com/ajax/libs/lunr.js/2.0.0/lunr.min.js:6:145)
    at http://localhost:4000/assets/js/search.js:36:29
    at _4ec (http://cdnjs.cloudflare.com/ajax/libs/dojo/1.10.4/dojo.js:15:128307)
    at _4e6 (http://cdnjs.cloudflare.com/ajax/libs/dojo/1.10.4/dojo.js:15:128171)
    at _4eb.resolve (http://cdnjs.cloudflare.com/ajax/libs/dojo/1.10.4/dojo.js:15:129632)
    at _4f2 (http://cdnjs.cloudflare.com/ajax/libs/dojo/1.10.4/dojo.js:15:128913)
    at _4ec (http://cdnjs.cloudflare.com/ajax/libs/dojo/1.10.4/dojo.js:15:128523)
    at _4e6 (http://cdnjs.cloudflare.com/ajax/libs/dojo/1.10.4/dojo.js:15:128171)
    ----------------------------------------
    rejected at _4f2 (http://cdnjs.cloudflare.com/ajax/libs/dojo/1.10.4/dojo.js:15:128948)
    at _4ec (http://cdnjs.cloudflare.com/ajax/libs/dojo/1.10.4/dojo.js:15:128559)
    at _4e6 (http://cdnjs.cloudflare.com/ajax/libs/dojo/1.10.4/dojo.js:15:128171)
    at _4eb.resolve (http://cdnjs.cloudflare.com/ajax/libs/dojo/1.10.4/dojo.js:15:129632)
    at _4f2 (http://cdnjs.cloudflare.com/ajax/libs/dojo/1.10.4/dojo.js:15:128913)
    at _4ec (http://cdnjs.cloudflare.com/ajax/libs/dojo/1.10.4/dojo.js:15:128523)
    at _4e6 (http://cdnjs.cloudflare.com/ajax/libs/dojo/1.10.4/dojo.js:15:128171)
    at _4eb.resolve (http://cdnjs.cloudflare.com/ajax/libs/dojo/1.10.4/dojo.js:15:129632)
    at _4f2 (http://cdnjs.cloudflare.com/ajax/libs/dojo/1.10.4/dojo.js:15:128913)
    at _4ec (http://cdnjs.cloudflare.com/ajax/libs/dojo/1.10.4/dojo.js:15:128588)
    ----------------------------------------
Error
    at Promise.then._4f9.then (http://cdnjs.cloudflare.com/ajax/libs/dojo/1.10.4/dojo.js:15:130120)
    at Object.getSearchJSON (http://localhost:4000/assets/js/search.js:33:16)
    at Object.searchText (http://localhost:4000/assets/js/search.js:62:22)
    at Object.searchfunc (http://localhost:4000/assets/js/search.js:89:18)
    at searchfunc (http://localhost:4000/assets/js/search.js:116:33)
    at HTMLInputElement.<anonymous> (http://localhost:4000/assets/js/search.js:121:21)"
```

`TypeError: Cannot read property '1' of undefined`, 
Un...I don't know what it is.

And part of my code.
```
        getSearchJSON: function(callback) {
            let self = this;
            let request = require('dojo/request');
            request.get(this.searchJsonUrl, {
                handleAs: "json"
            }).then(function(data) {
                self.searchJSON = data;
                let lunrjs = require('vonfry/lib/lunrjs');
                let index = lunrjs(function() {
                    this.field('title');
                    this.field('content');
                    this.field('link');
                    this.field('date');
                    this.field('excerpt');
                    this.field('categories');
                    this.field('tags');
                    this.field('search_omit');
                    this.ref('id');
                    for (let idx in data) {
                        let _d = data[idx];                    
                        _d['id'] = idx;
                        this.add(_d);
                    }
                });
                self.lunrIdx = index;
                callback.apply(self);
            });
```

**Comment by olivernn** [comment]
The document [reference must be a string](https://lunrjs.com/docs/lunr.Builder.html#ref), try this:

```javascript
_d['id'] = idx.toString()
```

**Comment by VonFry** [comment]
In chrome, idx is string for default.
And if I change it to string using `toString`, it also has the same problem

**Comment by olivernn** [comment]
Interesting, can you put together a simple test case that I can use to re-create the error?

**Comment by VonFry** [comment]
This is an error log in safari 
`undefined is not an object (evaluating 'this.invertedIndex[h][n][t]')`

**Comment by olivernn** [comment]
To be able to help I need to be able to re-create the issue myself. Try and put together an index and document that can be run in something like jsfiddle that also has the same issues.

**Comment by VonFry** [comment]
https://test.vonfry.name/lunrjs/

A test case.

**Comment by olivernn** [comment]
Could you try and narrow it down to just the document that is failing, and narrow that document down to just the field that is causing issues.

**Comment by VonFry** [comment]
I try to narrow it down.

The problem seems that it only happen when the content has some special word, but I cannot find which word is the problem...

https://test.vonfry.name/lunrjs
https://test.vonfry.name/lunrjs/search.json

**Comment by VonFry** [comment]
jsfiddle: https://jsfiddle.net/Vonfry/suu1ju5f/

**Comment by olivernn** [comment]
Ok, I've update the [fiddle](https://jsfiddle.net/suu1ju5f/10/) with a more minimal reproduction.

This looks like a regression from the 1.0.0 branch. It is because "constructor" is a property of all JavaScript objects, this causes issues when using objects as hashes.

I'll look at putting together a fix for this in the next few hours, thanks for reporting.

**Comment by olivernn** [comment]
I've just pushed [2.0.1](https://github.com/olivernn/lunr.js/releases/tag/v2.0.1) which includes a fix for this issue, please check it out and let me know if you still have problems...

**Comment by VonFry** [comment]
Thank you!! It can be run.

**Comment by MatthiasRMS** [comment]
I still have an issue with `add` since I've updated to 2.0.0 (and then 2.0.1). 
I've simplified it and now I have only this:

```
    var idx = lunr(function () {
        this.field('name')
      })
    
        var doc = {
          "name": "hello",
          "id": 1
        }
        idx.add(doc)
 
```

And in the console:

`Uncaught TypeError: idx.add is not a function`

**Comment by olivernn** [comment]
@MatthiasRMS this isn't at all related to the original issue, in the future please open a new issue rather than commenting on an unrelated issue.

Also, the error message is pretty clear here, `add` is not a function on `idx`. Since there is a major version bump you can expect some breaking changes in the API, this is probably the largest and is well [documented](https://lunrjs.com/guides/upgrading.html#index-building).

`add` must be called within the function passed to the `lunr` function, i.e.

```javascript
var idx = lunr(function () {
  this.field('name')
  this.add({ name: "hello", id: "1" })
})
```

**Comment by MatthiasRMS** [comment]
@olivernn my bad, I didn't see it in the doc. Sorry about that !
